In [1]:
import os
import sys
import platform

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from astropy.time import Time

In [2]:
gp_table = pd.read_table('crab_gp_kaz_pulses_final.csv', sep='\t')

In [3]:
gp_table.head(30)

,Date,Time start,MJD,"Median, Jy","amp of gp, Jy","W50, point","W10, point","E, Jy*ms","Tay, ms","STD, Jy"
0,13.02.2010,20:26:28.9413394,55240.686525,1719.973935,45.817525,8.41105,63.16855,36500.669054,2.4576,7.172373
1,04.09.2010,07:08:21.3085403,55443.131314,1719.899290,35.812760,17.00090,30.15760,73356.128234,2.4576,7.332353
2,04.09.2010,07:08:21.3085403,55443.131314,1719.899290,32.077480,8.15030,39.28385,35092.405294,2.4576,7.332353
3,05.09.2010,07:04:25.4187240,55444.128588,1719.846590,78.662550,11.70395,49.80325,51731.646994,2.4576,7.883726
4,05.09.2010,07:04:25.4187240,55444.128588,1719.846590,35.034450,2.57025,25.17355,11084.963004,2.4576,7.883726
5,05.09.2010,07:04:25.4187240,55444.128588,1719.846590,27.937190,1.71350,15.39170,7360.088081,2.4576,7.883726
6,06.09.2010,07:00:29.5241603,55445.127027,1719.808575,57.915495,11.30165,49.67660,49376.170563,2.4576,7.790818
7,06.09.2010,07:00:29.5241603,55445.127027,1719.808575,42.729465,7.09240,25.42685,30721.535496,2.4576,7.790818
8,06.09.2010,07:00:29.5241603,55445.127027,1719.808575,38.445795,11.54005,20.52475,49865.547799,2.4576,7.790818
9,07.09.2010,06:56:33.6273651,55446.124262,1719.884080,35.654100,8.85060,65.93995,38185.122732,2.4576,6.136468
10,07.09.2010,06:56:33.6273651,55446.124262,1719.884080,29.229210,3.80695,38.00245,16364.634536,2.4576,6.136468
11,08.09.2010,06:52:37.7309112,55447.120789,1719.784030,64.693060,5.96000,31.16335,26137.764142,2.4576,8.741115
12,08.09.2010,06:52:37.7309112,55447.120789,1719.784030,51.449110,16.76250,42.87475,72966.870244,2.4576,8.741115
13,08.09.2010,06:52:37.7309112,55447.120789,1719.784030,39.731580,4.05280,31.87855,17525.059250,2.4576,8.741115
14,08.09.2010,06:52:37.7309112,55447.120789,1719.784030,34.660450,2.35420,14.67650,10150.657708,2.4576,8.741115
15,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,121.161705,19.33275,54.60850,87470.846210,2.4576,8.060292
16,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,43.267475,8.77610,27.79595,38027.348291,2.4576,8.060292
17,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,41.933825,2.33185,25.03945,10096.397939,2.4576,8.060292
18,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,41.162785,6.89125,24.76380,29824.539459,2.4576,8.060292
19,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,38.794595,18.24505,28.82405,78856.296035,2.4576,8.060292
20,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,36.871485,1.78800,6.62305,7719.402104,2.4576,8.060292
21,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,34.687375,18.33445,21.00900,79057.622489,2.4576,8.060292
22,09.09.2010,06:48:41.8374290,55448.118707,1719.858245,31.467055,5.02875,14.11775,21644.026927,2.4576,8.060292
23,11.09.2010,06:40:50.0363769,55450.112943,1720.034850,31.991470,14.14010,42.95670,60884.158138,2.4576,4.874699
24,11.09.2010,06:40:50.0363769,55450.112943,1720.034850,28.635000,6.31015,30.37365,27118.065387,2.4576,4.874699
25,12.09.2010,06:36:54.1340866,55451.109830,1719.899890,111.648630,19.42215,63.82415,87423.246552,2.4576,7.515294
26,12.09.2010,06:36:54.1340866,55451.109830,1719.899890,65.269410,17.39575,44.06675,76319.192311,2.4576,7.515294
27,12.09.2010,06:36:54.1340866,55451.109830,1719.899890,57.179930,13.51430,40.93030,59021.696561,2.4576,7.515294
28,12.09.2010,06:36:54.1340866,55451.109830,1719.899890,35.272010,7.24140,26.24635,31235.854655,2.4576,7.515294
29,12.09.2010,06:36:54.1340866,55451.109830,1719.899890,34.174680,10.59390,19.99580,45668.328867,2.4576,7.515294

In [101]:
resul_tab = pd.DataFrame(columns=[
    'MJD_mean',
    'W50_mean',
    'STD'])

In [102]:
srez_mjd = np.asarray(gp_table['MJD'])
srez_w50 = np.asarray(gp_table['W50, point'])

In [103]:
from math import ceil

def chunk(arr, size):
    return list(
        map(lambda x: arr[x * size:x * size + size],
            list(range(0, ceil(len(arr) / size)))))

In [106]:
srez_mjd_30 = chunk(srez_mjd, 10)
srez_w50_30 = chunk(srez_w50, 10)

In [107]:
srez_mjd_30[-1]

array([58198.58755594, 58198.58715988, 58198.58711932, 58198.5889382 ,
       58198.58733248, 58198.58854638, 58245.46078625])

In [108]:
srez_w50_30[-1]

array([ 7.0191 ,  4.0788 ,  1.9899 ,  4.97475,  7.01415,  6.22215,
       20.7207 ])

In [109]:
idx = 0
for mjd, w50 in zip(srez_mjd_30, srez_w50_30):
    resul_tab.loc[idx] = [
            np.mean(mjd),
            np.mean(w50),
            np.std(w50)]
    idx +=1

In [110]:
resul_tab

         MJD_mean   W50_mean       STD
0    55478.235626  16.841385  3.093863
1    55499.876659  13.111065  4.634691
2    55506.658186  12.316095  3.542499
3    55512.043530  13.675860  2.835064
4    55532.786607  14.257980  2.965268
5    55545.950525  15.498945  4.424959
6    55668.115931  23.432310  8.446552
7    55893.698453  13.726845  2.838732
8    55931.894002   9.006525  4.038732
9    55953.135609   9.692595  2.098865
10   55965.402225  12.865050  2.739146
11   56250.920342  15.674670  6.731023
12   56467.826658  15.138585  3.705272
13   56506.919577  12.581415  4.495655
14   56580.916715  17.520525  6.388730
15   56678.649705   8.179875  1.917884
16   56697.796824   6.855255  0.962320
17   56703.980305   5.533110  1.661331
18   56707.869431   6.158790  2.123734
19   56710.462159   5.626170  1.350064
20   56716.446062   6.345900  1.323897
21   56719.636889   5.071275  1.404978
22   56721.631794   4.707945  0.736305
23   56727.216095   5.269275  0.561096
24   56729.410173   5.031180  0.682351
25   56733.200342   6.054840  1.024810
26   56736.391166   6.263730  1.227760
27   56743.671092   6.156315  1.145873
28   56749.255920   6.383025  1.400331
29   56753.444581   6.306300  1.692690
..            ...        ...       ...
82   58087.990817   9.317385  0.978389
83   58102.850060   9.049590  1.173724
84   58113.919512   7.522515  1.435244
85   58116.811976   7.462125  1.208287
86   58119.903598   7.367085  1.319080
87   58123.792686   7.409160  1.734303
88   58125.587663   7.205220  1.937701
89   58127.183760   6.968610  1.513696
90   58127.881654   5.612310  1.977967
91   58128.779232   7.017615  1.171428
92   58130.773484   8.070480  1.698514
93   58131.272514   6.377085  2.032854
94   58132.369179   6.831000  1.562554
95   58133.964913   6.156315  1.357530
96   58135.361203   6.815655  2.375694
97   58136.457879   6.463215  1.583797
98   58137.555525   6.669630  2.403517
99   58138.552690   7.266105  1.416007
100  58139.250759   6.428565  2.257537
101  58140.945931   6.116715  1.722772
102  58146.231106   7.077510  1.510710
103  58148.724602   8.196210  1.412400
104  58159.794654   8.132270  0.961627
105  58179.639706   8.133840  1.441280
106  58182.631529   8.427870  1.592599
107  58187.119468   7.538850  0.676279
108  58194.399494   6.633495  1.072674
109  58197.890220   6.616170  0.985563
110  58198.588129   5.674680  1.736226
111  58205.283920   7.431364  5.673206

[112 rows x 3 columns]

In [111]:
resul_tab.to_csv('W50_bin_10.csv', sep='\t', header=True, index=False)

### Разбиение по дням(календарным)

In [149]:
gp_table['Time_series'] = pd.to_datetime(gp_table['Date'], format='%d.%m.%Y', errors='ignore')
gp_table = gp_table.set_index('Time_series')

In [155]:
bin_size = '10D'
gp_min = gp_table.resample(bin_size).min().dropna()
gp_max = gp_table.resample(bin_size).max().dropna()
gp_mean = gp_table.resample(bin_size).mean().dropna()
gp_std = gp_table.resample(bin_size).std().dropna()

In [156]:
res_table = pd.concat([gp_min['MJD'],gp_mean['MJD'], gp_max['MJD'],gp_mean['W50, point'], gp_std['W50, point']], axis=1).dropna()

In [157]:
res_table.columns = ['MJD_min', 'MJD_mean','MJD_max','W50_mean', 'W50_std']

In [158]:
res_table

                  MJD_min      MJD_mean       MJD_max   W50_mean    W50_std
Time_series
2010-09-05   55444.128679  55448.317914  55451.110267  16.697835   3.521177
2010-09-15   55455.098916  55460.370859  55463.078020  13.022743   4.744145
2010-10-15   55486.013491  55487.385536  55488.009987  15.994688   4.173809
2010-10-25   55495.987190  55499.914147  55502.968549  15.675413   3.172705
2010-11-04   55504.962164  55508.132700  55511.943977  14.950238   4.376516
2010-11-14   55515.933693  55517.927707  55519.922167  15.571050   7.872711
2010-11-24   55523.911674  55528.523203  55532.886893  15.408113   3.232107
2010-12-04   55533.882354  55538.014999  55542.859555  16.859700   3.113463
2010-12-14   55543.856044  55547.347051  55550.838059  15.030675   5.246768
2011-01-03   55567.791465  55568.289510  55568.787555  26.366175   0.878545
2011-01-13   55577.764022  55580.257364  55582.750707  33.741675   4.651737
2011-02-22   55621.642205  55621.642473  55621.642741  35.763750   2.044104
2011-08-01   55777.216384  55778.878984  55782.203047  12.983850   2.365908
2011-09-20   55828.078149  55828.742840  55830.071501  22.024200   3.860395
2011-11-09   55874.949148  55875.946968  55877.942392  14.945700   3.532408
2011-11-19   55884.922953  55887.166960  55887.915241  18.526613   3.824012
2011-11-29   55893.896876  55898.430804  55902.872437  14.911650   3.131462
2011-12-09   55911.847553  55911.847696  55911.847838  11.993850   0.301015
2011-12-19   55914.841134  55919.826684  55923.816422  14.369850   3.070219
2011-12-29   55925.810310  55930.706253  55933.789410  12.994200   5.210078
2012-01-08   55936.779462  55940.104040  55942.764271   7.230300   1.851309
2012-01-18   55944.757835  55948.747831  55953.734673   9.616685   2.927099
2012-01-28   55954.730611  55958.609404  55963.706787  11.240350   3.429717
2012-02-07   55964.704094  55966.698834  55968.694048  15.551663   3.294631
2012-02-17   55974.677174  55979.663653  55982.655968  12.894750   3.367921
2012-05-07   56054.457519  56057.449828  56060.442137  12.959100  11.501587
2013-05-02   56417.464432  56419.459159  56420.456815  18.014700   6.360781
2013-05-12   56428.434377  56430.677868  56431.426266  12.866288   5.220636
2013-05-22   56435.414321  56436.744910  56437.410700  17.815050   9.632264
2013-06-01   56445.388743  56448.878267  56451.370877  20.163825   2.825135
...                   ...           ...           ...        ...        ...
2017-11-07   58063.956139  58068.881582  58072.933056   8.987611   2.458856
2017-11-17   58073.928392  58078.648142  58082.905487   9.196255   2.071865
2017-11-27   58084.898311  58089.234711  58092.878375   9.166369   1.786833
2017-12-07   58093.873631  58097.610964  58102.850836   9.017366   1.733426
2017-12-17   58103.846430  58108.624563  58113.820660   8.078081   1.546819
2017-12-27   58115.813644  58118.504981  58121.798994   7.582019   1.352057
2018-01-06   58124.788979  58128.973704  58133.766545   7.783996   1.638618
2018-01-16   58134.762004  58137.736634  58139.750168   7.689240   1.390584
2018-01-26   58145.731656  58148.417789  58151.717545   8.148037   1.494143
2018-02-05   58163.683266  58163.683921  58163.684369   7.799963   1.686783
2018-02-25   58178.641734  58180.026566  58182.632829   8.251347   2.371833
2018-03-07   58185.622800  58189.952340  58193.602593   7.406505   1.639005
2018-03-17   58194.597912  58199.033812  58203.575407   6.893588   1.617819
2018-03-27   58204.571042  58206.699381  58208.561902   7.487617   1.444256
2018-04-06   58215.540520  58219.021950  58223.520786  10.490868   1.884448
2018-04-16   58224.516176  58227.615797  58232.494708  13.206423   2.900552
2018-04-26   58234.489917  58237.920256  58243.464934  14.673186   4.799944
2018-05-06   58245.459801  58249.448863  58253.438354  17.524547   5.960690
2018-05-16   58257.427572  58261.202615  58263.411514  15.200743   4.859260
2018-05-26   58264.407938  58267.085051  58272.387052  12.697271   6.237511
2018-06-05   58274.379779  58278.646557  58282.359417  13.611400   4.432529
2018-06-15   58284.352997  58288.508620  58292.332237  11.645288   4.618716
2018-06-25   58296.319479  58298.730656  58302.304687   8.179875   1.200359
2018-07-05   58304.299477  58309.883485  58313.273181   8.482072   1.684030
2018-07-15   58315.267596  58319.399934  58323.246026   8.969754   3.024530
2018-07-25   58326.238351  58330.014040  58333.219472  10.131236   4.210902
2018-08-04   58335.213387  58338.405165  58341.197457  17.422020   5.584760
2018-10-03   58394.052438  58394.052703  58394.052968   8.442225   0.206511
2018-10-13   58405.022902  58407.516080  58410.009259  11.880000   3.241165
2018-10-23   58416.989718  58418.186583  58418.984953  16.297380   7.070068

[178 rows x 5 columns]

In [159]:
res_table.to_csv('W50_bin_10_sigma.csv', sep='\t', header=True, index=False)

### Разбиение по календарным дням с использованием временного индекса для определения MJD

In [42]:
# Создание новой колонки
gp_table['DateTime'] = None
for idx, row in gp_table.iterrows():
    gp_table.loc[idx,'DateTime'] = str(row['Date']) + ' ' + str(row['Time start'])

In [43]:
gp_table.head()

,Date,Time start,"point of gp, point",MJD,amp_GP,"E, Jy*ms","W50, point","W10, point","Period, s","Numpointwin, point","Tay, ms","Median, adc u","STD, adc u",DateTime
0,09.09.2010,06:48:41.8374290,45640,55448.118449,1841.01995,87457.272738,19.32975,54.61335,5.988578,2430,2.4576,1719.858245,8.060292,09.09.2010 06:48:41.8374290
1,12.09.2010,06:36:54.1340866,36629,55451.110002,1831.54852,87408.392547,19.41885,63.82035,5.988594,2430,2.4576,1719.899890,7.515294,12.09.2010 06:36:54.1340866
2,17.09.2010,06:17:14.6399831,41855,55456.096499,1825.78580,84223.745508,18.77040,39.25350,5.988624,2430,2.4576,1719.914380,7.683190,17.09.2010 06:17:14.6399831
3,17.10.2010,04:19:17.6313152,27361,55486.014177,1952.33752,102649.316153,21.39390,59.65245,5.988894,2430,2.4576,1719.841330,11.058682,17.10.2010 04:19:17.6313152
4,17.10.2010,04:19:17.6313152,3239,55486.013491,1859.31040,57609.915837,12.60765,41.72355,5.988894,2430,2.4576,1719.841330,11.058682,17.10.2010 04:19:17.6313152

In [44]:
gp_table['Time_series'] = pd.to_datetime(gp_table['DateTime'], format='%d.%m.%Y %H:%M:%S.%f', errors='ignore')
gp_table['Time_series'] -= pd.Timedelta('4 hour') # to UTC
gp_table = gp_table.set_index('Time_series')

In [53]:
bin_size = '10D'
gp_mean = gp_table.resample(bin_size).mean().dropna()
gp_std = gp_table.resample(bin_size).std().dropna()

In [54]:
res_table = pd.concat([gp_mean['W50, point'], gp_std['W50, point']], axis=1).dropna()

In [55]:
res_table = res_table.reset_index()

In [56]:
res_table['MJD_start'] = None

In [57]:
for index, row in res_table.iterrows():
    time_utc_start = Time(str(row['Time_series']).replace(' ', 'T'), precision=7)
    res_table.loc[index,'MJD_start'] = str(time_utc_start.mjd)

In [58]:
res_table.columns = ['Time_start' ,'W50_mean', 'W50_std', 'MJD_start']
res_table = res_table[['MJD_start', 'W50_mean', 'W50_std']]

In [59]:
res_table

             MJD_start   W50_mean    W50_std
0    55448.11715089617  19.173000   0.351496
1    55478.11715089617  15.109380   3.952801
2    55488.11715089617  15.674175   3.959295
3    55498.11715089617  11.947980   4.139750
4    55508.11715089617  14.008005   3.091864
5    55518.11715089617  14.550525   2.145609
6    55528.11715089617  14.269950   2.942122
7    55538.11715089617  13.580325   2.451736
8    55558.11715089617  21.525075   8.417929
9    55618.11715089617  21.879000  12.996520
10   55888.11715089617  12.878250   2.688617
11   55898.11715089617  11.447700   2.246015
12   55918.11715089617  12.618787   4.735863
13   55928.11715089617   8.421600   3.474825
14   55938.11715089617   8.880300   2.983271
15   55948.11715089617   7.566900   1.560344
16   55958.11715089617  11.798100   2.128494
17   55968.11715089617  13.302300   5.726040
18   55998.11715089617  20.390700   3.955757
19   56408.11715089617  23.685750   1.498076
20   56418.11715089617  10.281150   3.262166
21   56428.11715089617  14.513400   7.832050
22   56468.11715089617  13.579830   1.891754
23   56478.11715089617  13.739220   3.527747
24   56498.11715089617   7.021575   0.598531
25   56508.11715089617  10.157400   3.437175
26   56538.11715089617  14.575275   5.792796
27   56558.11715089617  18.361200   1.339671
28   56568.11715089617  13.810500   1.339549
29   56668.11715089617   9.173340   2.069983
..                 ...        ...        ...
80   57408.11715089617  10.360350   0.763039
81   57418.11715089617   7.131300   1.164143
82   57428.11715089617  10.192050   2.678075
83   57468.11715089617  14.450700   1.470678
84   57478.11715089617  17.740800   1.791319
85   57488.11715089617  10.934550   0.595030
86   57498.11715089617  11.412225   3.326254
87   57508.11715089617   8.302140   1.861119
88   57518.11715089617  12.801250   1.810576
89   57528.11715089617  14.236200   6.161175
90   57538.11715089617  11.210760   0.391463
91   57988.11715089617  11.738100   0.806779
92   58008.11715089617   8.969400   0.619581
93   58018.11715089617   9.920625   1.313967
94   58028.11715089617  10.534765   1.239553
95   58038.11715089617   9.472725   1.495124
96   58048.11715089617   9.461735   0.837281
97   58058.11715089617   9.091500   2.157566
98   58068.11715089617   9.517500   1.230610
99   58078.11715089617   9.494100   1.210239
100  58088.11715089617   9.322971   1.179167
101  58098.11715089617   8.772638   1.053279
102  58108.11715089617   7.649472   1.349383
103  58118.11715089617   6.833784   1.854181
104  58128.11715089617   6.800227   1.892848
105  58138.11715089617   7.010121   1.968799
106  58148.11715089617   8.039142   1.040985
107  58178.11715089617   8.090775   1.347163
108  58188.11715089617   6.846125   0.962024
109  58198.11715089617   5.610707   1.639941

[110 rows x 3 columns]

In [60]:
res_table.to_csv('W50_bin_10.csv', sep='\t', header=True, index=False)

### Реализация алгоритма Максима
Сделать можно, например, вот так. У нас интервал 55400-58300, 2900 дней. Можно просто определять, попадает ли импульс в какой-то бин (MJD-55400)/10(30). Нацело делить на размер бина в днях, это целое число даст номер бина. Ну и для каждого бина заводишь массив, в который скидываешь w50, которые относятся к соотв. бину. После этого считаешь стат. величины для каждого такого массива, т.е. каждого бина.

In [10]:
dect_res = {}
bin_size = 10

In [11]:
for idx, row in gp_table.iterrows():
    bin_num = (row['MJD'] - 55240)//bin_size
    try:
        dect_res[bin_num].append(row['W50, point'])
    except KeyError:
        dect_res[bin_num] = []
        dect_res[bin_num].append(row['W50, point'])

In [12]:
resul_tab = pd.DataFrame(columns=[
    '№ bin',
    'MJD_mean',
    'W50_mean',
    'STD',
    'len bin'])

In [13]:
idx = 0
for key in dect_res.keys():
    resul_tab.loc[idx] = [
        key,    
        (key + 0.5)*bin_size + 55240,
        np.mean(dect_res[key]),
        np.std(dect_res[key]),
        np.size(dect_res[key])
    ]
    idx +=1

In [14]:
resul_tab = resul_tab.sort_values(by=['№ bin'])

In [15]:
resul_tab.head()

   № bin  MJD_mean   W50_mean       STD  len bin
0    0.0   55245.0   8.411050  0.000000      1.0
1   20.0   55445.0   8.799466  5.808416     22.0
2   21.0   55455.0  10.967228  5.330297     18.0
3   22.0   55465.0   7.084950  4.124938     12.0
4   24.0   55485.0  10.143462  5.342371     26.0

In [16]:
resul_tab.to_csv('W50_bin_'
                 + str(bin_size)
                 + '_maxm_final.csv', sep='\t', header=True, index=False)